#spring.application.name=K_Means_Clustering

spring:
  application:
    name: K_Means_Clustering
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_updates: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: ${db_username}
    url: ${db_url}
    password: ${db_password}


server:
  error:
    include-message: always

